version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    working_dir: /var/www/api
    command: flask run --host=0.0.0.0 --eager-loading
    environment:
      FLASK_ENV: "development"
    volumes:
      - type: bind
        source: "./app"
        target: "/var/www/api"
    ports:
      - "5001:5000"
