version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    working_dir: /var/www/api
    command: flask run --host=0.0.0.0 --eager-loading
    environment:
      FLASK_ENV: "development"
    volumes:
      - type: bind
        source: "./app"
        target: "/var/www/api"
    ports:
      - "5001:5000"
    networks:
      - backend

  postgresql:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: stockless
      POSTGRES_USER: stockless
      POSTGRES_DB: stockless
    networks:
      - backend
    container_name: database
    ports:
      - "5432:5432"

networks:
  backend:
    driver: bridge
