version: '3.9'

services:
  api:
    build:
      context: .
      target: dev
    volumes:
      - ./api/:/api
    container_name: backend
    command: sh -c 'npm run start:docker'
    ports:
      - "3000:3000"
    networks:
      - server
    working_dir: /api
    env_file: .env
    depends_on:
      - database

  database:
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    container_name: database
    volumes:
      - ./infra/database:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - server

networks:
  server:
    driver: bridge